#!/usr/bin/env bash

# echo '<pre>' > fragment.html
# cat coming_up.json >> fragment.html
# echo '</pre>' >> fragment.html

cat coming_up.json | jq '.events[:4] as $events | {"events": $events}' > coming_up_short.json

jinja -d coming_up.json jinja-mobi.j2 > fragment.html

jinja -d coming_up_short.json jinja-mobi.j2 > fragment_short.html
