#!/usr/bin/env bash

# echo '<pre>' > fragment.html
# cat coming_up.json >> fragment.html
# echo '</pre>' >> fragment.html

cat coming_up.json | jq '.events[:2] as $events | {"events": $events}' > coming_up_short.json

jinja2 --format=json jinja-mobi.j2 coming_up.json > fragment.html

jinja2 --format=json jinja-mobi.j2 coming_up_short.json > fragment_short_prep.html

# should be a better way
cat fragment_short_prep.html | sed s/min-width:.300px\;.width/min-width:\ 280px\;\ max-width/g > fragment_short.html

# visible cross check

colordiff -b fragment_short_prep.html fragment_short.html






