#!/usr/bin/env bash

API_BASE="https://api.mobilize.us/v1"
ORG_ID=1071
CENTER=48103
RADIUS=25
CHUNK=20

NOW=$(date +%s)
# look for thing at least an hour out
NOW=$(($NOW + 3600))
START="gte_${NOW}"

# look ahead up to one week = 86400 X 7
THEN=$(($NOW + 604800))
# or two weeks!
THEN=$(($THEN + 604800))
END="lte_${THEN}"

# http "${API_BASE}/organizations/${ORG_ID}/events?&zipcode=${CENTER}&max_dist=${RADIUS}&per_page=${CHUNK}&timeslot_start=${START}&timeslot_start=${END}" \

# http "${API_BASE}/organizations/${ORG_ID}/events?&zipcode=${CENTER}&max_dist=${RADIUS}&per_page=${CHUNK}&timeslot_start=${START}" \

# http "${API_BASE}/organizations/${ORG_ID}/events?zipcode=${CENTER}&max_dist=${RADIUS}&event_types=INTEREST_FORM&per_page=${CHUNK}" \

# EVENTS
EVENTS=$(http "${API_BASE}/organizations/${ORG_ID}/events?organization_id=${ORG_ID}&zipcode=${CENTER}&max_dist=${RADIUS}&per_page=${CHUNK}&timeslot_start=${START}&timeslot_start=${END}" \
  | jq '.data[] | .id as $id | .title as $title | .featured_image_url as $event_image | .browser_url as $url | .event_type as $event_type | .description as $description | .location.locality as $locality | .timeslots[0].start_date as $startish | .sponsor | .event_feed_url as $org_feed | .name as $org_name  | {$id,$title,$url,$locality,$startish,$event_image,$event_type,$org_name,$org_feed,org_type,is_virtual,$description}' \
  | jq -s . \
  | jq '. | sort_by(.startish)' \
  | jq 'map( . + { "event_start": ( .startish | strflocaltime("%A, %b %d @ %-I%p") ) | tostring } )' \
  | jq '. | {"events": .}' | jq '.events')

# echo -E "${EVENTS}"

# INTEREST FORMS that no matter what the start date but they must end after NOW (in the future)
#### Leaving out description field since we do not use it in jinja-mobi.j2 AND
#### when it is present adn there are newlines or other special chars in it we have jq 'add' issues
INTEREST_FORMS=$(http "${API_BASE}/organizations/${ORG_ID}/events?organization_id=${ORG_ID}&event_types=INTEREST_FORM&zipcode=${CENTER}&max_dist=${RADIUS}&per_page=${CHUNK}&timeslot_end=gte_${NOW}" \
  | jq '.data[] | .id as $id | .title as $title | .featured_image_url as $event_image | .browser_url as $url | .event_type as $event_type |  .location.locality as $locality | .timeslots[0].start_date as $startish | .sponsor | .event_feed_url as $org_feed | .name as $org_name  | {$id,$title,$url,$locality,$startish,$event_image,$event_type,$org_name,$org_feed,org_type,is_virtual}' \
  | jq -s . \
  | jq '. | sort_by(.startish)' \
  | jq 'map( . + { "event_start": ( .startish | strflocaltime("%A, %b %d @ %-I%p") ) | tostring } )' \
  | jq '. | {"events": .}' | jq '.events')

# echo -E "${INTEREST_FORMS}"

echo -E "${EVENTS}${INTEREST_FORMS}" | jq -s 'add' | jq '. | {"events": .}'


# cat coming_up.json | jq '. | sort_by(.startish)' | jq '.[] | .startish | strflocaltime("%A, %B %-d, %-I:%M %p")'^C
# | jq 'map( . + { "event_start": ( .startish | strflocaltime("%A, %b %d @ %-I:%M%P") ) | tostring } )' \
