#!/usr/bin/env bash

API_BASE="https://api.mobilize.us/v1"
ORG_ID=1071
CENTER=48103
RADIUS=100
CHUNK=20

NOW=$(date +%s)
# look for thing at least an hour out
NOW=$(($NOW + 3600))
START="gte_${NOW}"

# look ahead up to one week = 86400 X 7
THEN=$(($NOW + 604800))
# or two weeks!
THEN=$(($THEN + 604800))
END="lte_${THEN}"

# http "${API_BASE}/organizations/${ORG_ID}/events?&zipcode=${CENTER}&max_dist=${RADIUS}&per_page=${CHUNK}&timeslot_start=${START}&timeslot_start=${END}" \

http "${API_BASE}/organizations/${ORG_ID}/events?&zipcode=${CENTER}&max_dist=${RADIUS}&per_page=${CHUNK}&timeslot_start=${START}" \
  | jq '.data[] | .id as $id | .title as $title | .featured_image_url as $event_image | .browser_url as $url | .event_type as $event_type | .description as $description | .location.locality as $locality | .timeslots[0].start_date as $startish | .sponsor | .event_feed_url as $org_feed | .name as $org_name  | {$id,$title,$url,$locality,$startish,$event_image,$event_type,$org_name,$org_feed,org_type,is_virtual,$description}' \
  | jq -s . \
  | jq '. | sort_by(.startish)' \
  | jq 'map( . + { "event_start": ( .startish | strflocaltime("%A, %b %d @ %-I%p") ) | tostring } )' \
  | jq '. | {"events": .}'



# cat coming_up.json | jq '. | sort_by(.startish)' | jq '.[] | .startish | strflocaltime("%A, %B %-d, %-I:%M %p")'^C
# | jq 'map( . + { "event_start": ( .startish | strflocaltime("%A, %b %d @ %-I:%M%P") ) | tostring } )' \